In [8]:
import pandas as pd
import re 

df = pd.read_json('../output/news.json')
df.head()

,article_id,body,title,footer,created_at,image,reactions,author
0,a5153640,\n \n (van de schoolleiding da...,"\n Haga Lyceum: ""Iedereen geschorst!""",\n \n @Ronaldo |\n \n \n 26...,2020-05-26 10:40:47,https://image.gscdn.nl/image/1848bd0092_ee887f...,81,@Ronaldo
1,a5153638,"\n \n Opeens heb het, je wordt...",\n Boa’s geen wapenstok en peppersp...,\n \n @Spartacus |\n \n \n ...,2020-05-26 10:40:47,None,28,@Spartacus
2,a5153631,\n \n Met gratis schoongemaakt...,\n Terras CoronaCafe vanavond al OPEN!,\n \n @Pritt Stift |\n \n \n ...,2020-05-26 10:40:47,https://image.gscdn.nl/image/632d411685_1Coron...,85,@Pritt Stift
3,a5153632,\n \n De redactieluiken zijn w...,\n Nog geen woord op Volkskrant.nl ...,\n \n @Van Rossem |\n \n \n ...,2020-05-26 10:40:47,https://image.gscdn.nl/image/4a7b51fd35_296BCB...,28,@Van Rossem
4,a5153617,"\n \n De interviewer is gek, v...",\n GS Vrije Geluiden: ‘Het coronabe...,\n \n @Van Rossem |\n \n \n ...,2020-05-26 10:40:47,None,31,@Van Rossem

In [9]:
# apply date_func and time_func on "footer" column to seprate article time and date and store them in seprate columns 
def date_func(text):
    date = re.findall(r'[0-9]{2}[-|\/]{1}[0-9]{2}[-|\/]{1}[0-9]{2}', text)
    return date
def time_func(text):
        time = re.findall(r'[0-9]{2}[:|\/][0-9]{2}', text)
        return time
    
df = df.replace('\n','', regex=True)
df['publication_date']= df['footer'].apply(lambda x : date_func(x))
df['publication_time']= df['footer'].apply(lambda x : time_func(x))
df.head(2)

,article_id,body,title,footer,created_at,image,reactions,author,publication_date,publication_time
0,a5153640,(van de schoolleiding dan hè...,"Haga Lyceum: ""Iedereen geschorst!""",@Ronaldo | 26-05-20 | 0...,2020-05-26 10:40:47,https://image.gscdn.nl/image/1848bd0092_ee887f...,81,@Ronaldo,[26-05-20],[09:59]
1,a5153638,"Opeens heb het, je wordt boa...",Boa’s geen wapenstok en pepperspra...,@Spartacus | 26-05-20 |...,2020-05-26 10:40:47,None,28,@Spartacus,[26-05-20],[09:00]

In [11]:
%%html
<style> 
table td, table th, table tr {text-align:left !important;}
</style>



| key | Description |example|
| --- | --- | --- |
|article_id | the unique id of aritcles |
|body | The full (plain!) text of the document, excluding title |
|title|title of the document|
|created_at|date and time of scraping|
|image| link to the image|
|reactions|number of reactions to each article|
|author|author|
|publication_time| time of publication|
|publication_date|date of publication, format: dd-mm-yy|